name: Enrique Test 101
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

env:
   Name: Enrique
jobs:
  Enrique-is-Awesome:
    runs-on: ubuntu-latest
    steps:
      - run: " for i in {1..100}; do echo $Name ${{ github.event_name }}; done"
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
